site_name: SuperWeights
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

repo_name: superweights
repo_url: https://github.com/yourusername/superweights

nav:
  - Home: index.md
  - User Guide:
    - Installation: guide/installation.md
    - Quick Start: guide/quickstart.md
    - Examples: guide/examples.md
  - API Reference:
    - Model: api/model.md
    - Quantization: api/quantization.md
    - Utils: api/utils.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
